lab for setting the COBOL Check environment
openmainframeproject/cobol-programming-course pull request #311
Opened 2023-08-20 15:03 UTC by ashiskumarnaik

## Proposed changes

lab for setting the COBOL Check environment

Fixes # (issue)

## Type of change

What type of changes does your PR introduce to the COBOL Programming Course? _Put an `x` in the boxes that apply._

- [ ] Bug fix (change which fixes one or more issues)
- [x] New feature (change which adds functionality or features to the course)
- [ ] Translations (change which adds or modifies translations of the course)
- [ ] Documentation (change which modifies documentation related to the course)
- [ ] This change requires an update to the course's z/OS environment

## Checklist:

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [Contributing Guideline](https://github.com/openmainframeproject/cobol-programming-course/blob/master/CONTRIBUTING.md)
- [ ] I have included a title and description for this PR
- [x] I have DCO-signed all of my commits that are included in this PR
- [ ] I have tested it manually and there are no regressions found
- [ ] I have commented my code, particularly in hard-to-understand areas (if appropriate)
- [ ] I have made corresponding changes to the documentation (if appropriate)

2023-10-21 09:19 UTC, ashiskumarnaik commented
@tanto259 Can you review it ?

2023-11-04 00:43 UTC, tanto259 requested changes
Just some minor fixes, then I think we're good to go. Thanks, Ashis!

2023-11-04 00:43 UTC, tanto259 commented on COBOL Programming Course #4 - Testing/COBOL Programming Course #4 - Testing.md
> +Cobol-check supports fine-grained unit-testing. Let's provide some contextual information to make the meaning of that clearer. This is a popular level of test automation; lets call it a pyramid or a
COBOL Check supports ... let's call it ...

> The key idea is that we need to test our software at multiple levels of abstraction as we move higher in the diagram, we are testing larger pieces of software lower in the diagram, we are testing smaller pieces of software.

This sentence sounds weird... possible to rephrase?

2023-11-04 00:43 UTC, tanto259 commented on COBOL Programming Course #4 - Testing/COBOL Programming Course #4 - Testing.md
> +TESTCASE - identifies a test case. The description is echoed in the output of the test run.
Might need an extra line separating this two, or we can change this to bullet point

2023-11-04 00:43 UTC, tanto259 commented on COBOL Programming Course #4 - Testing/COBOL Programming Course #4 - Testing.md
> +Assert: Validate the anticipated outcome of the test
We should probably change this to bullet point as well so that it will be easier to read

2023-11-04 00:43 UTC, tanto259 commented on COBOL Programming Course #4 - Testing/COBOL Programming Course #4 - Testing.md
> +3. Open your vs code with the same team configuration file with the Learn Cobol folder which you have used in course 2. If not, you can also download it from https://github.com/openmainframeproject/c
Open your VS Code ... with the Learn COBOL folder ...

2023-11-04 00:43 UTC, tanto259 commented on COBOL Programming Course #4 - Testing/COBOL Programming Course #4 - Testing.md
> +4. click on the icon of Zowe Explore an extension on the left sidebar of VS code.
Zowe Explorer ... of VS Code

2023-11-04 00:43 UTC, tanto259 commented on COBOL Programming Course #4 - Testing/COBOL Programming Course #4 - Testing.md
> +*Figure 4.  Zowe explorer*
Zowe Explorer

2023-12-04 13:52 UTC, merged